### PR TITLE
Recording and sharing audio

### PR DESCRIPTION
**Pull request by dtext**
Work in progress. Any thoughts on this so far? I included some comments in the commit messages.

### CODE REVIEW

**Comment by denniseffing** [comment]
We should consider working on #11 before we think of supporting different filetypes. This includes some programmatic way of distinguishing the abilities of specific storage providers. For instance, the storage implementations themselves should tell the developer which filetypes it supports. 

A way to do this might be splitting the current upload function of every provider into multiple functions like upload_screenshot, upload_audio, upload_text etc. pp. Regarding your comment in 1f426f6, this would even enable us to change the URL of the file, should it direct to a direct download instead of an embedded audio player.

**Comment by dtext** [comment]
Well, the support for audio is already there, so it's kind of too late to ask for a resolution of #11 "before we think about this". For now, I would just separate the config options, so we have `<mediatype>_provider`.

As far as your suggestion goes: I had something like that in mind, too. It would be a good way to know if a storage provider supports a specific media type. We could just read the provider setting for the media type from the config and call it's `upload_<mediatype>()` function. If we get an `AttributeError` or `NotImplementedError`, we let the user know that they need to change their config accordingly.
Internally, all the different functions could just call the same `_upload()` function, or do some adjustments beforehand or afterwards.

I only see a weak dependency between the issue and this pull request though, it will be very easy to change the code produced here later on. The status of that issue should not hold us back from making progress here.

**Comment by dtext** [comment]
What do you think about the other points raised in the commit messages?
- the workflow is the same for every type of medium: create, upload, get shareable link, notify user. We should follow the DRY principle and make this code easily available to all commands
- audio files are currently uncompressed, which is far from ideal. Do you know of any other codec/library that might be suitable here?

**Comment by florianluediger** [comment]
Maybe a workaround for uploading compressed audio files would be recording the audio in WAVE and convert the files afterwards into a compressed form, for example mp3. Not ideal, but better than uploading large files in my opinion.

**Comment by dtext** [comment]
If we don't use installed software for transcoding, this does not reduce our problem. We would still need to decode wav and then encode to ogg/opus. As far as mp3 goes, I'd rather not [risk it](http://stackoverflow.com/questions/2425724/whats-the-current-mp3-royalties-licensing-situation).

Another option is of course using installed software like ffmpeg, which further complicates distribution.

To me, it seems that there is no obvious and easy solution, so we really need to dive in and maybe even create our own python bindings for opuslib or something like that (vorbis, etc.) in the future.

**Comment by dtext** [comment]
This is ready to be merged now. The file size is a slight issue for slow internet connections, but we shouldn't optimize prematurely. I'd rather push out this feature now and work on a solution to our audio compression problem later, so we don't have to constantly worry about updating this branch. After all, this PR is a few months old, and we do have a solution now, even though it's not ideal.

**Pull request merged**
